import questionary

FOREX_URL = "https://market.nbebank.com/market/banks/index.php"
SPINNERS = [
    "dots",
    "dots2",
    "dots3",
    "dots4",
    "dots5",
    "dots6",
    "dots7",
    "dots8",
    "dots9",
    "dots10",
    "dots11",
    "dots12",
    "dots8Bit",
    "line",
    "line2",
    "pipe",
    "simpleDots",
    "simpleDotsScrolling",
    "star",
    "star2",
    "flip",
    "hamburger",
    "growVertical",
    "growHorizontal",
    "balloon",
    "balloon2",
    "noise",
    "bounce",
    "boxBounce",
    "boxBounce2",
    "triangle",
    "arc",
    "circle",
    "squareCorners",
    "circleQuarters",
    "circleHalves",
    "squish",
    "toggle",
    "toggle2",
    "toggle3",
    "toggle4",
    "toggle5",
    "toggle6",
    "toggle7",
    "toggle8",
    "toggle9",
    "toggle10",
    "toggle11",
    "toggle12",
    "toggle13",
    "arrow",
    "arrow2",
    "arrow3",
    "bouncingBar",
    "bouncingBall",
    "smiley",
    "monkey",
    "hearts",
    "clock",
    "earth",
    "material",
    "moon",
    "runner",
    "pong",
    "shark",
    "dqpb",
    "weather",
    "christmas",
    "grenade",
    "point",
    "layer",
    "betaWave",
    "aesthetic",
]
STYLE = questionary.Style(
    [
        ("qmark", "fg:red bold"),
        ("question", "fg:yellow bold"),
        ("highlighted", "fg:#673AB7 bold"),
        ("answer", "fg:#2196f3 bold"),
        ("pointer", "fg:#27781e bold"),
        # ("highlighted", "fg:#27781e bold"),
        # ("selected", "fg:#cc5454 bold"),
        ("separator", "italic fg:#7c7d6b"),
        ("instruction", "fg:#f02634"),
        ("disabled", "fg:#858585 italic"),
        ("qmark", "fg:#673ab7 bold"),
        ("text", "fg:#68687d"),
    ]
)
